### PR TITLE
various fixes, including compatibility fix for autosubmit

### PR DESCRIPTION
**Pull request by etiennesky**
Hi @plesager with current implementation, I cannot change the value of the IFS, NEMO, post and diag dirs when running with autosubmit.

I have commented those variables in the mn4 config, but I think the best would be to let the user set them outside of the config file and have the default still in the config file

something like (untested) would be ok with me

[[ -z ${IFSRESULTS0:-} ]] && export IFSRESULTS0='/scratch/ms/nl/$USER/ECEARTH-RUNS/${EXPID}/output/ifs/${LEGNB}'

### CODE REVIEW

**Comment by etiennesky** [comment]
let me know what you think and I can update the branch

**Comment by etiennesky** [comment]
just found out that my test for monthly legs in nemo_post.sh was not done properly, it does not work yet, working on it.

**Comment by etiennesky** [comment]
Hi @plesager  fixed the 2 issues mentioned above. please see if the env. variable strategy is ok for you

**Comment by plesager** [comment]
thanks @etiennesky for testing/fixing NEMO postprocessing. The way you modified your config files to be able to set some variables through env variable is totally fine.

**Comment by etiennesky** [comment]
thanks for merging it!

**Pull request merged**
